---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  minReadySeconds: 4
  replicas: 2
  selector:
    matchLabels:
      app: cart
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: cart-pod
      labels:
        app: cart
    spec:
      containers:
        - name: cart-container
          image: vemulasai/cart:1.0.0
          ports:
            - containerPort: 80
             
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  minReadySeconds: 4
  replicas: 2
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: order-pod
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: vemulasai/order:1.0.0
          ports:
            - containerPort: 80
              
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: cart-service 
spec: 
  minReadySeconds: 4 
  replicas: 2 
  selector: 
    matchLabels: 
      app: cart 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  template:
    metadata: 
      name: cart-pod 
      labels: 
        app: cart 
    spec:
      containers:
        - name: cart-container 
          image: vemulasai/cart-service:1.0.0
          ports:
            - containerPort: 80
                            
