--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: catalog-svc 
spec: 
  type: ClusterIP 
  selector:
    app: catalog 
  ports:
    - name: catalog-port 
      port: 80
      protocol: TCP
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: order-svc 
spec: 
  type: ClusterIP 
  selector:
    app: order 
  ports:
    - name: order-port 
      port: 80
      protocol: TCP      
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: cart-svc 
spec: 
  type: ClusterIP 
  selector:
    app: cart
  ports:
    - name: cart-port 
      port: 80
      protocol: TCP      