---
apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: replicas-node
  labels:
    app: jenkins
spec:
  minReadySeconds: 4 
  replicas: 4 
  selector: 
    matchExpressions:
      - key: app 
        operator: In 
        values:
          - jenkins 
      - key: ver 
        operator: In 
        values:
          - "1.78"    
  template: 
    metadata: 
      name: jenkins-pod 
      labels: 
        app: jenkins 
        ver: "1.78"
    spec: 
      containers: 
        - image: jenkins/jenkins:lts-jdk11
          name: jenkins-cont 
          ports: 
            - containerPort: 8080
              protocol: TCP 
              name: webport