---
apiVersion: v1 
kind: Service 
metadata: 
  name: node-port
  labels: 
    task: nodeporttask
spec: 
  type: NodePort
  selector:
    app: jenkins 
    ver: "1.78"
  ports:
    - name: nodeport-svc
      targetPort: 8080 
      port: 35000
      nodePort: 32001  