--- 
apiVersion: v1 
kind: Namespace 
metadata: 
  name: task-namespace
--- 
apiVersion: batch/v1 
kind: CronJOb 
metadata: 
  name: cron-task
  namespace: task-namespace
spec:
  schedule: "30 * * * 1-5"
  backoffLimit: 4 
  jobTemplate:
    metadata: 
      name: cronjob-pod 
      namespace: task-namespace
    spec: 
      backoffLimit: 4 
      template: 
        metadata: 
          name: task-cron 
          namespace: task-namespace 
          labels: 
            app: nginx 
        spec: 
          containers: 
            - name: cron-container 
              image: alpine:3 
              command: 
                - sleep 
                - 1s  
          
   