---
apiVersion: v1 
kind: Pod 
metadata:
  name: pvc-task-volume 
  labels:
    app: sql  
spec: 
  containers: 
    - name: mysql-container  
      image: mysql:8-debian
      ports: 
        - containerPort: 3306 
          protocol: TCP 
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops 
      resources: 
        requests: 
          memory: "124Mi"
          cpu: "25m"
        limits: 
          memory: "135Mi"
          cpu: "35m"
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql    
  volume: 
    - name: mysql-vol 
      persistentVolumeClaim:
        claimName: pvc-task 
        readOnly: false
 

