--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: basicpod
spec:
  containers:
    - image: nginx:1.23
      name: nginx-contianer
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "24m"
        limits:
          memory: "145Mi"
          cpu: "30m"  