---
apiVersion: v1
kind: Pod 
metadata: 
  name: lables-pod
  labels:
    ver: "1.23"
    app: nginx
spec: 
  containers: 
    - name: labels-cont
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1 
kind: Pod  
metadata: 
  name: pod-2
  labels: 
    app: nginx 
    ver: "1.24"
spec:         
  containers:
    - name: labels-cont1
      image: nginx:1.23 
      ports:
        - containerPort: 80
          protocol: TCP 