--- 
apiVersion: v1
kind: Pod 
metadata:
  name: nginxjenkinspod
spec:
  containers:
    - image: jenkins/jenkins:lts-jdk11
      name: jenkinscontainer 
      ports:
        - containerPort: 8080 
          name: jenkinsport
          protocol: TCP
      resources:
        requests:
          memory: "124Mi"
          cpu: "20m"
        limits: 
          memory: "128Mi"
          cpu: "30m" 
    - image: nginx:1.23
      name: nginxcontianer 
      ports:
        - containerPort: 80
          name: nginxcontainer
          protocol: TCP       
      resources:
        requests:
          memory: "24Mi"
          cpu: "20m"
        limits: 
          memory: "30Mi"
          cpu: "30m"  