---                                                           
apiVersion: v1
kind: Pod
metadata:
  name: ntiertask
  labels:
    enviroment: dev
spec:
  containers:
    - name: pod1
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP
          name: webport
      resources:
        requests:
          memory: "24Mi"
          cpu: "20m"
        limits:
          memory: "32Mi"
          cpu: "24m"
---