---
apiVersion: v1
kind: ReplicationController 
metadata:
  name: replication-nginx
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx 
        ver: "1.2"
    spec:
      containers:
        - image: nginx:1.23
          name: rc-cont 
          ports:
            - containerPort: 80
              protocol: TCP   
