--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: restartpolicy-pod
spec:
  containers: 
    - image: alpine:3
      name: restart-never
      command:
        - sleep
        - "2"      
  restartPolicy: Never
---
apiVersion: v1
kind: Pod 
metadata: 
  name: norestartpolicy-pod
spec:
  containers: 
    - image: alpine:3
      name: restart-norestartpolicy
      command:
        - sleep
        - "2"      
