---
apiVersion: v1
kind: Namespace
metadata:
  name: task-namespace
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-batch-task
  namespace: task-namespace
spec:
  backoffLimit: 5
  manualSelector: true
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: job-pod-batch
      namespace: task-namespace
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
        - image: nginx
          name: nginx-container-batch
          ports:
            - containerPort: 80
              name: webport-job
              protocol: TCP
          command:
            - sleep
            - 1s
      restartPolicy: OnFailure
